# Generated by Django 4.1.3 on 2022-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="private_key",
            field=models.TextField(
                default=b"-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQC+QACjDtn206H3VQELfPBnRPUazoZyenPC9tm6rQkDeybwClS5\n1v7octnzaHwduxGEyJYpHKmJkaQ41rYblTXk8/1AKxKUEn0v29QeABcme2TG/XR4\nJaMHXpW0IQsxqkNQkhpJQBWkYcar/WcDXwpnHKLa40KJnfOHa4zStpB/FQIDAQAB\nAoGADOp48Jj9RLPM8ubnNYGzq3sjvcBoIcT8729FTFZbfoxBkjnNUzmMoDjN4afG\nB1mwIIjiouNigiesU7yF6/z3BdhpB3LQRIANcrcv8bhLiQ4rWNAja85G6xLY9Ug5\nQc2MCrcw2Q0FAg/JahzAhz6NUEASlgsbBaxMidwj1vpbOSECQQDTJGnK97L/zpHP\nXmrCQ+IE1NFMlqndwuVItyctA34aXGd9E+QzenYWDeHzm19SRF7JU4vD8te94PLb\nGEov6b8hAkEA5qtN61HS+OEewL7HS0ZAPJlAyv1PmZSm9CLPzTukYidsiubg/kaf\n2BJ/FfE2lGMFeC/B3tJyox0OtOw0gnCFdQJAVdLUSdM7aC2AKUlYndRX99zFopsP\nOvvwlQkVnH9x76clzbqbJK2feEF2Wb4LFfaCjNUv15tLRHw+Wv5ZkXYy4QJBAJYS\ncXleHNJLNITWGjdBF13Vny/xqi4TZqODWor9+K7bU2TzXQJR1IDxV7lg28+itNZC\ny/E6Hdc9emn/GxKaPlkCQQDE+3tq+7UKgQ3vq+yZHPlPdSOmyx6tM19Rs4mKrXT8\n+K2ViLmWBRbSAUTrUY25YxhW1yqZmdY3pQdzVRbRRLZ3\n-----END RSA PRIVATE KEY-----"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="public_key",
            field=models.TextField(
                default=b"-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+QACjDtn206H3VQELfPBnRPUa\nzoZyenPC9tm6rQkDeybwClS51v7octnzaHwduxGEyJYpHKmJkaQ41rYblTXk8/1A\nKxKUEn0v29QeABcme2TG/XR4JaMHXpW0IQsxqkNQkhpJQBWkYcar/WcDXwpnHKLa\n40KJnfOHa4zStpB/FQIDAQAB\n-----END PUBLIC KEY-----"
            ),
        ),
    ]
