# Generated by Django 4.1.4 on 2023-01-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_users_email_remove_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='private_key',
            field=models.TextField(default='-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQD1ZuXOq9DE4L/P1qQ3hPiULmfjPFFjh93zpiJioo4ZnDO+NCL+\nb96fsv9XLQUReYJhz1hYyuReK0W49P7tZiQwKiO23jtq6cCJFd2tWSXysd7Mn77f\n5HbEUPMvdAmllGTaYR9wQoSjXxnlw+07a9L4lLEnc8/xHji8Fk3lvY0i4QIDAQAB\nAoGAHkecioRDxc8vi78h0yHqpCoXsn+yUTQmDFbO/lmta/aMoeb//GIkV5M4E3Mg\nIXhbQKNbdNVQGViAiWJdhEBqrXLhVgvoN+jPhUcYFNYIsMMpdU+FsOmwXEL/IS60\nf06AhODCjCkReNY/aT9PEaG6R9uc4cPbxVMplRhFXzuok7sCQQD3FURP/Kky2hv4\npzscawMoQg92t1eCt+r6TjxXDiJXXjPde+3AW9HAPzmabvo/YVr2+1LxFVwIp1R8\nl70GC5jfAkEA/kIZbnfffNOGFqHg/PBpeMuHpL9nGPi8lPtWffG+8eBI/RBuPmxx\nU6Cs/nnnTcg6e7vlfMard+ZVi1sYdan8PwJAIntLT0ZZbolVwfvEmhCtHh8p/U1U\n3x8/obLtZNDKJhs1bcFvypqFySiJp225asLxaOpmBtMORv7jIYgjjwZrTQJACfZ9\nGJ8J2tJPBsQBFOg2ucz/26zEVW4ptYzDrtuyJ7gqJABo0XleV3CMVsxgC+Q0pnSO\nYX1HasNTxsojAzlN8QJBAKTC7SMShfp4oUypuyti7tmkOB1R5Z6SiTLqwvjAFCy3\nXWN3GzOIizCqnpnv92TJAjn8fCg36Hhtt9FOIi5uGhI=\n-----END RSA PRIVATE KEY-----'),
        ),
        migrations.AlterField(
            model_name='users',
            name='public_key',
            field=models.TextField(default='-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD1ZuXOq9DE4L/P1qQ3hPiULmfj\nPFFjh93zpiJioo4ZnDO+NCL+b96fsv9XLQUReYJhz1hYyuReK0W49P7tZiQwKiO2\n3jtq6cCJFd2tWSXysd7Mn77f5HbEUPMvdAmllGTaYR9wQoSjXxnlw+07a9L4lLEn\nc8/xHji8Fk3lvY0i4QIDAQAB\n-----END PUBLIC KEY-----'),
        ),
    ]
