# Generated by Django 4.1.4 on 2023-02-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_users_private_key_alter_users_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='users',
            name='public_key',
        ),
    ]
